environment:
  sdk: '^3.8.0'

name: notes_app_bloc
description: "A Flutter notes app with BLoC and Hive"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true